[tools]
node = "22"
pnpm = "9"
go = "1.23"
python = "3.13"
"npm:opencommit" = "3.2"
"pipx:git-remote-codecommit" = "latest"
"pipx:claudesync" = "latest"
rust = "latest"
deno = "latest"
bun = "1.2"
"npm:@openai/codex" = "0.20"

[settings]
experimental = true
