[tools]
go = "1.26"

[tasks.install_tools]
description = "Install dev tools with brew"
run = "brew bundle install --file dot_Brewfile"
dir = "dotfiles"

[tasks.setup_keyboard]
description = "Setup keyboard via karabiner"
run = """
go run .
launchctl kickstart -k gui/$(id -u)/org.pqrs.service.agent.Karabiner-Console-User-Server
"""
dir = "karabiner"

[tasks.link_dotfiles]
description = "Link dotfiles with chezmoi"
depends = ['install_tools']
run = 'chezmoi --source "$PWD" init --apply'

[tasks.apply_duti]
description = "Apply duti settings"
run = "duti defaults.duti"
dir = "duti"

[tasks.setup_env]
description = "Setup environment"
alias = "init"
depends = ['install_tools', 'setup_keyboard', 'link_dotfiles', 'apply_duti']
