[project]
name = "transaction-processor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "openai>=1.84.0",
    "pydantic>=2.11.5",
]
