# MacBook Pro only; loaded by ../Brewfile

cask("audacity")
cask("battle-net")
cask("bettermouse")
cask("elgato-capture-device-utility")
cask("elgato-control-center")
cask("elgato-stream-deck")
cask("firefox")
cask("iina")
cask("kindle-comic-converter")
cask("obs")
cask("parallels")
cask("qflipper")
cask("raspberry-pi-imager")
cask("rode-central")
cask("sublime-text")
cask("teeworlds")
cask("via")
cask("visual-studio-code")
